Add migration test config for new framework (not enabled yet)

diff --git a/tester/migration-test-config.yaml b/tester/migration-test-config.yaml
--- a/tester/migration-test-config.yaml
+++ b/tester/migration-test-config.yaml
@@ -99,7 +99,38 @@ uninstall: |
   helm del --purge aws-ebs-csi-driver
 
 test: |
-  go get -u github.com/onsi/ginkgo/ginkgo
-  export KUBECONFIG=$HOME/.kube/config
-  export AWS_AVAILABILITY_ZONES=us-west-2a
-  ginkgo -p -nodes=32 -v --focus="\[ebs-csi-e2e\] \[single-az\]" tests/e2e -- -report-dir=$ARTIFACTS
+  # TODO known test failures to skip temporarily
+  # - should not allow expansion of pvcs without AllowVolumeExpansion property
+  #   - Test passes but cleanup fails, need https://github.com/kubernetes/kubernetes/pull/81107
+  # - (block volmode) Verify if offline PVC expansion works / should resize volume when PVC is edited while pod is using it
+  #   - NodeExpand for BlockVolumes not well-defined, need more investigation and possibly https://github.com/container-storage-interface/spec/issues/380
+  # - should provision storage with mount options
+  #   - Known bug, need https://github.com/kubernetes/kubernetes/pull/80191 but not yet in a patch release
+  cd ./tests/e2e-migration
+  go test -v -timeout 0 ./... -kubeconfig=$HOME/.kube/config -report-dir=$ARTIFACTS -ginkgo.focus="\[ebs-csi-migration\]" -ginkgo.skip="\[Disruptive\]\
+    |should.not.allow.expansion\
+    |block.volmode.+volume-expand\
+    |should.provision.storage.with.mount.options\
+    |should.not.mount./.map.unused.volumes.in.a.pod" -gce-zone=us-west-2a
+  TEST_PASS=$?
+  cd ../..
+
+  # There should have been no calls to the in-tree driver kubernetes.io/aws-ebs but many calls to ebs.csi.aws.com
+  # Find the controller-manager log and read its metrics to verify
+  NODE=$(kubectl get node -l kubernetes.io/role=master -o json | jq -r ".items[].metadata.name")
+  kubectl port-forward kube-controller-manager-$NODE 10252:10252 -n kube-system&
+  curl 127.0.0.1:10252/metrics -s | grep -a 'volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="ebs.csi.aws.com"'
+  CSI_CALLED=$?
+  curl 127.0.0.1:10252/metrics -s | grep -a 'volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs"'
+  INTREE_CALLED=$?
+
+  # TEST_PASS if tests passed, CSI was called, and In-tree was not called
+  if [ "$TEST_PASS" == 0 ] && [ "$CSI_CALLED" == 0 ] && [ "$INTREE_CALLED" == 1 ]; then
+      TEST_PASS=0
+  else
+      TEST_PASS=1
+  fi
+
+  if [[ $TEST_PASS -ne 0 ]]; then
+      exit 1
+  fi
